name: CI

on: 
    push:
        branches: ["main"]

jobs:
    build-docker-image:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: docker build . -t myshell:${{github.sha}}
          name: build docker image
        - uses: azure/docker-login@v1
          with:
            login-server: rajdummytest.azurecr.io
            username: mytoken
            password: ${{secrets.ACR_TOKEN}}
        
